name: CI

on:
  push:
  pull_request:
  schedule:
    - cron:  '0 0 1 * *'

jobs:
  CUDALucas:
    name: CUDALucas

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, ubuntu-22.04]
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - name: Before script
      run: |
        sed -i '/^GPU=/,/^fi/ s/^/# /' cudalucas.sh
        sed -i 's/ -flto//' cudalucas.sh
        sed -i '/^if ! COMPUTE=/,/^fi/ s/^/# /' cudalucas.sh
        sed -i 's/\/$COMPUTE/\/-gencode arch=compute_35,code=sm_35 -gencode arch=compute_50,code=sm_50 -gencode arch=compute_60,code=sm_60 -gencode arch=compute_70,code=sm_70/' cudalucas.sh
        sed -i '/^\.\/CUDALucas / s/^/# /' cudalucas.sh
        sed -i '/^nohup / s/^/# /' cudalucas.sh
        sed -i '/^python3 / s/^/# /' cudalucas.sh
        sed -i '/^crontab / s/^/# /' cudalucas.sh
    - name: Script
      run: bash -e -o pipefail -- cudalucas.sh ANONYMOUS
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: ${{ matrix.os }}_cudalucas
        path: |
          cudalucas/
    - name: ShellCheck
      run: bash -c 'shopt -s globstar; shellcheck -s bash **/*.sh || true'

  Mlucas:
    name: Mlucas

    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.cc == 'clang' }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, ubuntu-22.04]
        cc: [gcc, clang]
      fail-fast: false
    env:
      CC: ${{ matrix.cc }}
    steps:
    - uses: actions/checkout@v3
    - name: Before script
      run: |
        sed -i '/^[[:blank:]]*nohup / s/^/# /' mlucas.sh
        sed -i '/^python3 / s/^/# /' mlucas.sh
        $CC --version
    - name: Script
      run: |
        set -x
        bash -e -o pipefail -- mlucas.sh ANONYMOUS
        echo -e '## Warnings\n```' >> $GITHUB_STEP_SUMMARY
        grep 'warning:' mlucas_v*/obj/build.log | sed 's/\x1B\[\([0-9]\+\(;[0-9]\+\)*\)\?m//g' | awk '{ print $NF }' | sort | uniq -c | sort -nr >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
    - name: GCC analyzer
      if: ${{ matrix.os == 'ubuntu-22.04' && matrix.cc == 'gcc' }}
      run: |
        set -x
        cd mlucas_v*/obj/ && $CC -c -fdiagnostics-color -g -O3 -march=native -DUSE_THREADS -fanalyzer ../src/*.c |& tee analyzer.log
        make clean
        echo -e '## GCC analyzer\n```' >> $GITHUB_STEP_SUMMARY
        grep 'warning:' analyzer.log | sed 's/\x1B\[\([0-9]\+\(;[0-9]\+\)*\)\?m//g' | awk '{ print $NF }' | sort | uniq -c | sort -nr >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: ${{ matrix.os }}_${{ matrix.cc }}_mlucas
        path: |
          mlucas_v*/
    - name: ShellCheck
      run: bash -c 'shopt -s globstar; shellcheck -s bash **/*.sh || true'

