name: CI

on:
  push:
  pull_request:
  schedule:
    - cron:  '0 0 1 * *'

jobs:
  CUDALucas:
    name: CUDALucas

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, ubuntu-20.04]
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - name: Before script
      run: |
        sed -i '/^GPU=/,/^fi/ s/^/# /' cudalucas.sh
        sed -i '/^if ! COMPUTE=/,/^fi/ s/^/# /' cudalucas.sh
        sed -i 's/\/$COMPUTE/\/--generate-code arch=compute_35,code=sm_35 --generate-code arch=compute_50,code=sm_50/' cudalucas.sh
        sed -i '/^\.\/CUDALucas / s/^/# /' cudalucas.sh
        sed -i '/^nohup / s/^/# /' cudalucas.sh
        sed -i '/^python3 / s/^/# /' cudalucas.sh
        sed -i '/^crontab / s/^/# /' cudalucas.sh
    - name: Script
      run: bash -e -- cudalucas.sh ANONYMOUS
    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: ${{ matrix.os }}_cudalucas
        path: |
          cudalucas/
    - name: ShellCheck
      run: bash -c 'shopt -s globstar; shellcheck -s bash **/*.sh || true'

  Mlucas:
    name: Mlucas

    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.cc == 'clang' }}
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, ubuntu-20.04]
        cc: [gcc, clang]
      fail-fast: false
    env:
      CC: ${{ matrix.cc }}
    steps:
    - uses: actions/checkout@v2
    - name: Before script
      run: |
        sed -i '/^[[:blank:]]*nohup / s/^/# /' mlucas.sh
        sed -i '/^python3 / s/^/# /' mlucas.sh
        $CC --version
    - name: Script
      run: bash -e -- mlucas.sh ANONYMOUS
    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: ${{ matrix.os }}_${{ matrix.cc }}_mlucas
        path: |
          mlucas_v*/
    - name: ShellCheck
      run: bash -c 'shopt -s globstar; shellcheck -s bash **/*.sh || true'

