name: CI

on:
  push:
  pull_request:
  schedule:
    - cron:  '0 0 1 * *'

jobs:
  CUDALucas:
    name: CUDALucas

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, ubuntu-22.04]
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - name: Before script
      run: |
        sed -i '/^GPU=/,/^fi/ s/^/# /' cudalucas.sh
        sed -i 's/ -flto//' cudalucas.sh
        sed -i '/^if ! COMPUTE=/,/^fi/ s/^/# /' cudalucas.sh
        sed -i 's/\/$COMPUTE/\/-gencode arch=compute_35,code=sm_35 -gencode arch=compute_50,code=sm_50 -gencode arch=compute_60,code=sm_60 -gencode arch=compute_70,code=sm_70/' cudalucas.sh
        sed -i '/^\.\/CUDALucas / s/^/# /' cudalucas.sh
        sed -i '/^nohup / s/^/# /' cudalucas.sh
        sed -i '/^python3 / s/^/# /' cudalucas.sh
        sed -i '/^crontab / s/^/# /' cudalucas.sh
        gcc --version
    - name: Script
      run: bash -e -o pipefail -- cudalucas.sh ANONYMOUS
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: ${{ matrix.os }}_cudalucas
        path: |
          cudalucas/
    - name: ShellCheck
      run: bash -c 'shopt -s globstar; shellcheck -s bash **/*.sh || true'
    - name: Clang-Tidy
      run: cd cudalucas; clang-tidy -checks='bugprone-*,cert-*,clang-analyzer-*,concurrency-*,misc-const-correctness,misc-redundant-expression,misc-unused-*,performance-*,portability-*,readability-const-return-type,readability-container-*,readability-duplicate-include,readability-else-after-return,readability-make-member-function-cons,readability-non-const-parameter,readability-redundant-*,readability-simplify-*,readability-string-compare,readability-use-anyofallof' -header-filter='.*' *.c *.cu -- -Wall -O3 --cuda-gpu-arch=sm_35 || true

  GpuOwl:
    name: GpuOwl

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
        cxx: [g++, clang++]
      fail-fast: false
    env:
      CXX: ${{ matrix.cxx }}
      POSIXLY_CORRECT: 1
    steps:
    - uses: actions/checkout@v3
    - name: Before script
      run: |
        sed -i '/^GPU=/,/^fi/ s/^/# /' gpuowl.sh
        sed -i '/^time \./gpuowl-bench\.sh / s/^/# /' gpuowl.sh
        sed -i '/^nohup / s/^/# /' gpuowl.sh
        sed -i '/^python3 / s/^/# /' gpuowl.sh
        sed -i '/^crontab / s/^/# /' gpuowl.sh
        $CXX --version
    - name: Script
      run: bash -e -o pipefail -- gpuowl.sh ANONYMOUS
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: ${{ matrix.os }}_gpuowl
        path: |
          gpuowl/
    - name: ShellCheck
      run: bash -c 'shopt -s globstar; shellcheck -s bash **/*.sh || true'

  Mlucas:
    name: Mlucas

    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.cc == 'clang' }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, ubuntu-22.04]
        cc: [gcc, clang]
      fail-fast: false
    env:
      CC: ${{ matrix.cc }}
    steps:
    - uses: actions/checkout@v3
    - name: Before script
      run: |
        sed -i '/^[[:blank:]]*nohup / s/^/# /' mlucas.sh
        sed -i '/^python3 / s/^/# /' mlucas.sh
        $CC --version
    - name: Script
      run: |
        set -x
        bash -e -o pipefail -- mlucas.sh ANONYMOUS
        echo -e '## Warnings\n```' >> $GITHUB_STEP_SUMMARY
        grep 'warning:' mlucas_v*/obj/build.log | sed 's/\x1B\[\([0-9]\+\(;[0-9]\+\)*\)\?m//g' | awk '{ print $NF }' | sort | uniq -c | sort -nr >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
    - name: GCC analyzer
      if: ${{ matrix.os == 'ubuntu-22.04' && matrix.cc == 'gcc' }}
      run: |
        set -x
        cd mlucas_v*/obj/ && $CC -c -fdiagnostics-color -g -O3 -march=native -DUSE_THREADS -fanalyzer ../src/*.c |& tee analyzer.log
        make clean
        echo -e '## GCC analyzer\n```' >> $GITHUB_STEP_SUMMARY
        grep 'warning:' analyzer.log | sed 's/\x1B\[\([0-9]\+\(;[0-9]\+\)*\)\?m//g' | awk '{ print $NF }' | sort | uniq -c | sort -nr >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
    - name: Clang-Tidy
      if: ${{ matrix.cc == 'clang' }}
      run: |
        set -x
        cd mlucas_v*/obj/ && clang-tidy -checks='bugprone-*,cert-*,clang-analyzer-*,concurrency-*,misc-const-correctness,misc-redundant-expression,misc-unused-*,modernize-*,performance-*,portability-*,readability-const-return-type,readability-container-*,readability-duplicate-include,readability-else-after-return,readability-make-member-function-cons,readability-non-const-parameter,readability-redundant-*,readability-simplify-*,readability-string-compare,readability-use-anyofallof' -header-filter='.*' ../src/*.c -- -Wall -O3 -march=native -DUSE_THREADS |& tee clang-tidy.log
        echo -e '## Clang-Tidy\n```' >> $GITHUB_STEP_SUMMARY
        grep 'warning:' clang-tidy.log | sed 's/\x1B\[\([0-9]\+\(;[0-9]\+\)*\)\?m//g' | awk '{ print $NF }' | sort | uniq -c | sort -nr >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: ${{ matrix.os }}_${{ matrix.cc }}_mlucas
        path: |
          mlucas_v*/
    - name: ShellCheck
      run: bash -c 'shopt -s globstar; shellcheck -s bash **/*.sh || true'

